# Generated by Django 5.0.6 on 2024-07-08 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorPelicula',
            fields=[
                ('id_actor_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio_carrera', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado'), ('Muerto', 'Muerto')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroPelicula',
            fields=[
                ('id_genero_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('actor_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actorpelicula')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generopelicula')),
            ],
        ),
    ]
