# Generated by Django 5.0.6 on 2024-05-20 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_correo_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='admin',
            field=models.ForeignKey(default=1, limit_choices_to={'tipo': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
